---
title: Vladimir Serdechny Jewelry Modeling
timezone: UTC
collections:
  posts:
    title: Vladimir Serdechny Jewelry Modeling
    output: true
  uploads:
    title: Vladimir Serdechny Jewelry Modeling
    output: true
email: your-email@example.com
description: Jewelry 3d modeling for printing, cnc cutting, waxing; 3d modeling of watches, bracelets, earings, rings.
baseurl: ''
url: ''
twitter_username: serdechnyy
github_username: serdechnyy
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
includes:
- "/"
